version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./requirements/nginx/
  #     dockerfile: Dockerfile
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: ~/data/wordpress
  #       target: /var/www/html
  #   depends_on:
  #     - wordpress
  #     - certbot
  #   networks:
  #     - inception-network
  #   ports:
  #     - 443:443
        

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
      WORDPRESS_TITLE: "${WORDPRESS_TITLE}"
      WORDPRESS_ADMIN_USER: "${WORDPRESS_ADMIN_USER}"
      WORDPRESS_ADMIN_PASSWORD: "${WORDPRESS_ADMIN_PASSWORD}"
      WORDPRESS_ADMIN_EMAIL: "${WORDPRESS_ADMIN_EMAIL}"
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DB_NAME}"
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network
    ports:
      - 9000:9000

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DB_NAME: "${MYSQL_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - type: bind
        source: ~/data/mariadb
        target: /var/lib/mysql
    networks:
        - inception-network
    ports:
      - 3306:3306

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:latest
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: ./requirements/bonus/certbot/certs
  #       target: /etc/letsencrypt/live/$(DOMAIN_NAME)
  #   command: >
  #     -v
  #     certonly --noninteractive
  #     --agree-tos
  #     --cert-name slickstack
  #     -d ${DOMAIN_NAME}
  #     --register-unsafely-without-email
  #     --webroot -w /var/www/html/
  #   networks:
  #     - inception-network
  #   platform: linux/x86_64

networks:
  inception-network:
    name: inception-network
