version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - certbot
    networks:
      - inception-network
    ports:
      - 443:443
    restart: always

  certbot:
    build:
      context: ./requirements/bonus/certbot/
      dockerfile: Dockerfile
    command: >
      -v
      certonly --noninteractive
      --agree-tos
      --cert-name slickstack
      -d ${DOMAIN_NAME}
      --register-unsafely-without-email
      --webroot -w /var/www/html/
    container_name: certbot
    platform: linux/x86_64
    volumes:
      - type: bind
        source: ./requirements/bonus/certbot/certs
        target: /etc/letsencrypt/live/$(DOMAIN_NAME)

networks:
  inception-network:
    name: inception-network
