version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    networks:
      - inception-network
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/html
    depends_on:
      - wordpress
      - node
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    networks:
      - inception-network
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/html
    environment:
      DOMAIN_BLOG: ${DOMAIN_BLOG}
      WORDPRESS_VERSION: ${WORDPRESS_VERSION}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    networks:
        - inception-network
    volumes:
      - type: bind
        source: ~/data/mariadb
        target: /var/lib/mysql
    environment:
      MYSQL_DB_NAME: "${MYSQL_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer/
    ports:
      - 8080:8080
    networks:
      - inception-network
    depends_on:
      - mariadb
    restart: always

  pure-ftpd:
    container_name: pure-ftpd
    build:
      context: ./requirements/bonus/pure-ftpd/
    ports:
      - 21:21
      - 30000-30009:30000-30009
    networks:
      - inception-network
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/html
    environment:
      PUBLICHOST: ${FTP_PUBLICHOST}
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: ${FTP_USER_HOME}
    depends_on:
      - wordpress
    restart: always
    platform: linux/86_64

  node:
    container_name: node
    build:
      context: ./requirements/bonus/node/
    ports:
      - 3000:3000
    networks:
        - inception-network
    restart: always
    
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis/
    networks:
        - inception-network
    restart: always

networks:
  inception-network:
    name: inception-network
