services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    networks:
      - inception-network
    volumes:
      - wp-volume:/var/www/html/wp
      - node-volume:/var/www/html/node
    environment:
      - DOMAIN_BLOG
      - DOMAIN_GALLERY
    depends_on:
      wordpress:
        condition: service_healthy
      node:
        condition: service_completed_successfully
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    networks:
      - inception-network
    volumes:
      - wp-volume:/var/www/html/wp
    environment:
      - DOMAIN_BLOG
      - WORDPRESS_TITLE
      - WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASSWORD
      - WORDPRESS_ADMIN_EMAIL
      - WORDPRESS_EDITOR_USER
      - WORDPRESS_EDITOR_PASSWORD
      - WORDPRESS_EDITOR_EMAIL
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB_NAME
      - REDIS_HOST
      - REDIS_PORT
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-i:9000"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    networks:
        - inception-network
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_DB_NAME
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysql", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "use ${MYSQL_DB_NAME}"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer/
    networks:
      - inception-network
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  pure-ftpd:
    container_name: pure-ftpd
    build:
      context: ./requirements/bonus/pure-ftpd/
    ports:
      - 21:21
      - 30000-30009:30000-30009
    networks:
      - inception-network
    volumes:
      - wp-volume:/home/ftpuser
    environment:
      - FTP_PUBLICHOST
      - FTP_USER
      - FTP_PASSWORD
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always

  node:
    container_name: node
    build:
      context: ./requirements/bonus/node/
    networks:
      - inception-network
    volumes:
      - node-volume:/app
    restart: on-failure

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis/
    networks:
      - inception-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always

  datadoghq:
    image: gcr.io/datadoghq/agent:7
    container_name: datadoghq
    environment:
      - DD_API_KEY
      - DD_SITE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    security_opt:
      - seccomp:unconfined
    pid: "host"
    network_mode: "host"
    restart: always

volumes:
  wp-volume:
    name: wp-volume
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  node-volume:
    name: node-volume
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/node
  db-volume:
    name: db-volume
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception-network:
    name: inception-network
